PYTHON = python3

test_all:
	${PYTHON} -m unittest discover -v

test_bool:
	${PYTHON} -m unittest test_bool.py -v

test_comment:
	${PYTHON} -m unittest test_comment.py -v

test_conditional:
	${PYTHON} -m unittest test_conditional.py -v

test_function:
	${PYTHON} -m unittest test_functions.py -v

test_input:
	${PYTHON} -m unittest test_input.py -v

test_loops:
	${PYTHON} -m unittest test_loops.py -v

test_number:
	${PYTHON} -m unittest test_number.py -v

test_output:
	${PYTHON} -m unittest test_output.py -v

test_string:
	${PYTHON} -m unittest test_string.py -v