
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BOOLEAN DECREMENT DIVIDE ELIF ELSE EQUAL FALSE FOR FUNCTION GREATER GREATER_EQUAL ID IF IMPORT IN INCREMENT INPUT IN_PIPE LCURLY LESS LESS_EQUAL LPAREN LSQUARE MINUS MODULUS MULTIPLY NOT_EQUAL NUMBER NUMBER_LITERAL OBJECT OPERATOR OUT OUT_PIPE PLUS PRINT RCURLY RETURN RETURNS RPAREN RSQUARE SEMICOLON SEPARATOR SET STRING STRING_LITERAL THIS TRUE WHILEprogram : nextLine SEMICOLONprogram : nextLine : NUMBER_LITERALnextLine : IDnextLine : SET'
    
_lr_action_items = {'$end':([0,1,6,],[-2,0,-1,]),'NUMBER_LITERAL':([0,],[3,]),'ID':([0,],[4,]),'SET':([0,],[5,]),'SEMICOLON':([2,3,4,5,],[6,-3,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'program':([0,],[1,]),'nextLine':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> program","S'",1,None,None,None),
  ('program -> nextLine SEMICOLON','program',2,'p_program_nextLine','grammar_rules_simple.py',8),
  ('program -> <empty>','program',0,'p_program_empty','grammar_rules_simple.py',12),
  ('nextLine -> NUMBER_LITERAL','nextLine',1,'p_nextLine_number','grammar_rules_simple.py',17),
  ('nextLine -> ID','nextLine',1,'p_nextLine_id','grammar_rules_simple.py',21),
  ('nextLine -> SET','nextLine',1,'p_nextLine_equals','grammar_rules_simple.py',25),
]
