test_all:
	python3 -m unittest discover -v

test_bool:
	python3 -m unittest test_bool.py -v

test_comment:
	python3 -m unittest test_comment.py -v

test_conditionals:
	python3 -m unittest test_conditionals.py -v

test_function:
	python3 -m unittest test_function.py -v

test_input:
	python3 -m unittest test_input.py -v

test_loops:
	python3 -m unittest test_loops.py -v

test_number:
	python3 -m unittest test_number.py -v

test_output:
	python3 -m unittest test_output.py -v

test_string:
	python3 -m unittest test_string.py -v